### ISSUE TITLE
Not working in Chrome 87 on MacOS 10.14.6

### ISSUE THREAD

**Issue by s0lidarity** [trmcnvn/twitch-channel-points#14]
I'm no longer getting channel points redeemed automatically.

**Comment by TheOpponent** [comment]
Also not working in Vivaldi 3.5.2115.81 on Windows 10.

**Comment by WalrusPUNCH** [comment]
Google Chrome 87.0.4280.88, Windows 10  (19041.685)
Same problem

**Comment by bsrb** [comment]
Firefox 84.0 on Ubuntu, same issue.

**Comment by freedbrt** [comment]
I made patch https://github.com/trmcnvn/twitch-channel-points/pull/16
