### ISSUE TITLE
No longer auto-clicking

### ISSUE THREAD

**Issue by aidalgol** [trmcnvn/twitch-channel-points#19]
As of some time this week, the channel points bonuses are no longer being automatically clicked.  I am on Firefox 78.6.0esr.

**Comment by freedbrt** [comment]
Duplicate https://github.com/trmcnvn/twitch-channel-points/issues/14

**Comment by aidalgol** [comment]
Oh, sorry.  That issue sounded like it was talking about redeeming channel rewards, rather than the points bonuses.
