### ISSUE TITLE
Not working in Chrome 90

### ISSUE THREAD

**Issue by kimiioi** [trmcnvn/twitch-channel-points#24]
I'm no longer getting channel points redeemed automatically.

**Comment by Edson-Souza** [comment]
I also have this problem in Chrome Version 90.0.4430.212 (Official version) 64-bit

**Comment by ShadyDeth** [comment]
This isn't a chrome issue. Twitch changed the class name of the redeem button so the addon doesn't work. I've already submitted a pull request #23  with the fix.
