### ISSUE TITLE
Not working in Chrome 92

### ISSUE THREAD

**Issue by kimiioi** [trmcnvn/twitch-channel-points#27]
I'm no longer getting channel points redeemed automatically.

**Comment by fernandosutter** [comment]
Probably solved by Pull Request #28

**Comment by NoXPhasma** [comment]
https://github.com/trmcnvn/twitch-channel-points/pull/28 only fixed it for the English website language. As the aria-label is different for each language.

**Comment by Haeil-Kim** [comment]
not working korean website language my chorme version is  92.0.4515.107

**Comment by freedbrt** [comment]
The solution https://github.com/trmcnvn/twitch-channel-points/pull/30

**Comment by gaeaearth** [comment]
In Firefox (90.0.2) and Korean Twitch, it seems that the solution by freedbrt is not applied because I cannot automatically obtain the channel point bonus.
Please check this.

**Comment by freedbrt** [comment]
@gaeaearth how do you tested it ? Built source itself, or get it from store ?

**Comment by gaeaearth** [comment]
@freedbrt  From store (version 2021/07/28?9?). When I check auto-clicker.js of the addon, I cannot find your code. 
I think your solution is not applied addon yet.

**Comment by freedbrt** [comment]
@gaeaearth if you open this solution https://github.com/trmcnvn/twitch-channel-points/pull/30 you can see what it didn't merge.
