### ISSUE TITLE
NaN channel points

### ISSUE THREAD

**Issue by clayajohnson** [trmcnvn/twitch-channel-points#8]
Since adding this extension, a lot of the channels I follow say "NaN Channel Points". I'm hesitant to contact Twitch about this as I don't know what their stance on using auto-clickers for farming points is. Is there any chance it's related to the extension? Possibly because the auto clicker happens instantaneously, rather than with a minor delay - Twitch may infer from this behavior that the points are being auto-clicked. Any suggestions are welcome!

**Comment by trmcnvn** [comment]
This extension doesn't interact with the display of your points at all so I would say this is an issue with Twitch.

I doubt they care about these kinds of extensions.

**Comment by clayajohnson** [comment]
Cheers for the feedback! I'll get in touch with twitch re: points display.
